import type { Metadata } from "next";
import Link from "next/link";
import { ArrowUpRight, CalendarDays, MapPin, Sparkles, Ticket, Users } from "lucide-react";
import { getUpcomingEvents, getPastEvents } from "@/modules/events/queries";
import { Badge } from "@/components/ui/badge";

export const metadata: Metadata = { title: "Campus Events", description: "Discover what's happening across your college societies." };
export const revalidate = 3600;
function formatEventDate(date: Date) { return new Date(date).toLocaleDateString("en-US", { weekday: "short", month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }); }

export default async function EventsPage() {
  const [upcoming, past] = await Promise.all([getUpcomingEvents(), getPastEvents()]);
  return <main className="min-h-screen">
    <section className="relative overflow-hidden border-b border-foreground/10 surface-grid"><div className="absolute right-0 top-0 h-80 w-80 rounded-full bg-orange-400/10 blur-3xl" /><div className="relative mx-auto max-w-7xl px-5 pb-16 pt-14 sm:px-8 lg:px-10 lg:pt-20"><div className="flex items-center gap-2 text-[11px] font-black uppercase tracking-[.2em] text-orange-500"><Sparkles className="h-4 w-4" /> What&apos;s happening</div><h1 className="mt-5 max-w-4xl text-balance text-5xl font-black tracking-[-.065em] sm:text-7xl">Your campus, <span className="bg-gradient-to-r from-orange-500 to-rose-500 bg-clip-text text-transparent">in motion.</span></h1><p className="mt-5 max-w-2xl text-base leading-7 text-muted-foreground">There&apos;s always something going on. Find a workshop, a competition, a meetup, or just something fun to show up for.</p></div></section>
    <div className="mx-auto max-w-7xl px-5 py-12 sm:px-8 lg:px-10"><div className="mb-7 flex items-end justify-between"><div><div className="flex items-center gap-2"><h2 className="text-2xl font-black tracking-tight">What&apos;s coming up</h2><Badge variant="secondary" className="rounded-full">{upcoming.length}</Badge></div><p className="mt-1 text-sm text-muted-foreground">Pick something that sounds like you.</p></div><Ticket className="hidden h-6 w-6 text-orange-500 sm:block" /></div>
      {upcoming.length === 0 ? <div className="rounded-[2rem] border border-dashed p-20 text-center text-muted-foreground"><CalendarDays className="mx-auto mb-4 h-7 w-7 opacity-50" /><p className="font-semibold text-foreground">Nothing on the calendar yet.</p><p className="mt-1 text-sm">Keep an eye out — the next good thing could be added soon.</p></div> : <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{upcoming.map((event, index) => <Link key={event.id} href={`/events/${event.id}`} className="group overflow-hidden rounded-[1.6rem] border border-foreground/10 bg-card transition-all duration-300 hover:-translate-y-1 hover:border-orange-300/60 hover:shadow-2xl hover:shadow-orange-500/5">{event.imageUrl ? <div className="overflow-hidden"><img src={event.imageUrl} alt={event.title} className="aspect-[16/9] w-full object-cover transition-transform duration-500 group-hover:scale-[1.04]" /></div> : <div className="relative flex aspect-[16/9] items-end overflow-hidden bg-gradient-to-br from-orange-500/15 via-rose-500/10 to-transparent p-6"><div className="absolute -right-8 -top-8 h-32 w-32 rounded-full bg-orange-400/20 blur-2xl" /><CalendarDays className="relative h-9 w-9 text-orange-500" /></div>}<div className="p-6"><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 items-center gap-2"><span className="text-[10px] font-black text-muted-foreground">{String(index + 1).padStart(2, "0")}</span><Badge variant="secondary" className="max-w-[220px] truncate rounded-full">{event.society.name}</Badge></div><ArrowUpRight className="h-5 w-5 shrink-0 text-muted-foreground transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5" /></div><h3 className="mt-4 text-xl font-black tracking-tight">{event.title}</h3><p className="mt-2 line-clamp-2 text-sm leading-6 text-muted-foreground">{event.description}</p><div className="mt-6 space-y-2 border-t border-foreground/10 pt-4 text-xs text-muted-foreground"><div className="flex items-center gap-2"><CalendarDays className="h-3.5 w-3.5 text-orange-500" />{formatEventDate(event.date)}</div>{event.location && <div className="flex items-center gap-2"><MapPin className="h-3.5 w-3.5 text-orange-500" />{event.location}</div>}<div className="flex items-center gap-2"><Users className="h-3.5 w-3.5 text-orange-500" />Hosted by {event.society.name}</div></div><div className="mt-5 text-sm font-bold text-orange-600 transition group-hover:translate-x-0.5 dark:text-orange-400">Come along <ArrowUpRight className="ml-1 inline h-3.5 w-3.5" /></div></div></Link>)}</div>}
      {past.length > 0 && <section className="mt-20"><div className="mb-5"><h2 className="text-2xl font-black tracking-tight">Good times, already had</h2><p className="mt-1 text-sm text-muted-foreground">A little look back at what campus has been up to.</p></div><div className="grid gap-3 md:grid-cols-2">{past.map(event => <Link key={event.id} href={`/events/${event.id}`} className="group flex items-center justify-between rounded-2xl border border-foreground/10 bg-card p-4 transition hover:border-orange-300/60"><div><p className="font-bold">{event.title}</p><p className="mt-1 text-xs text-muted-foreground">{event.society.name} · {formatEventDate(event.date)}</p></div><ArrowUpRight className="h-4 w-4 text-muted-foreground transition group-hover:-translate-y-0.5 group-hover:translate-x-0.5" /></Link>)}</div></section>}
    </div>
  </main>;
}
